# Placeholders: [<time>, <command>, <prefix>]
messages:
  prefix: '&8[&c&loCooldowns&8]&r &8»&f'
  cooldown: '<prefix> You must wait &c<time>&f seconds to use this command again!'
  insufficient_permission: '<prefix> &cYou do not have permission to use this command.'
  reload: '<prefix> &aReloaded config in <time>ms!'

extra:
  # ocooldowns.bypass.[command_name|*]
  # If enabled, permissions won't work and therefore nobody will bypass cooldowns (not even OPs)
  disable_bypass_permissions: false

# "heal: 60" adds a '60 second cooldown to the command "/heal"
cooldowns:
  #command_name: seconds
  heal: 60
  feed: 30
  spawn: 10