name: oCooldowns
version: '1.0-Preview'
main: git.otrixzy.ocooldowns.OCooldowns
api-version: '1.21'
load: STARTUP

commands:
  ocooldowns:
    description: Main command for OCooldowns
    aliases:
      - ocooldown
      - cooldown
      - cooldowns